### ISSUE TITLE
User realtime display/hide columns

### ISSUE THREAD

**Issue by Dri372** [uasoft-indonesia/badaso#677]
Not at all.

The browse option is an admin setup (config of the crud) that display or hide fields permanently for this crud.

The proposed improvement is a user / real time option.

_Originally posted by @Dri372 in https://github.com/uasoft-indonesia/badaso/issues/620#issuecomment-1079431630_

**Comment by rizkiheryandi** [comment]
I think you can create a module/package/plugin for that, because it's oppinionated features, so if a developer want to use it, they can install the plugin.

You can see about the module/plugin development here https://badaso-docs.uatech.co.id/module-development/badaso-make-module

also you can see the structure from existing plugin, ex : 
https://github.com/uasoft-indonesia/badaso-post-module
https://github.com/uasoft-indonesia/badaso-commerce-module

Thank your for the feedback

**Comment by rizkiheryandi** [comment]
If you still have any question, we can re-open this issue later, thanks

**Comment by Dri372** [comment]
> it's oppinionated features

Full agree , I'll look at the module/plugin dev and let you know. That's said it's not a priority, I can live for a while with the "patch" given in the post.
